"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[kotlin]
disabled = true

[aws]
symbol = " "

[python]
python_binary = [["uv", "run", "--no-python-downloads", "python"]]
symbol = " "

[nodejs]
symbol = " "

[gcloud]
symbol = " "

[ruby]
symbol = " "

[java]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "

[gradle]
symbol = " "

[package]
symbol = "󰏗 "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = " "

